$dest = "C:\Users\pc\CSCOMPLEXES\strapicms\src\api\school-admin\services\academic-engine.ts"
$lines = @()
$lines += "// academic-engine.ts - Centralized Calculation Engine"
$lines += "// Single Source of Truth for all academic grade calculations."
$lines += ""
$lines += "const DEFAULT_GRADING_SCHEME: any[] = ["
$lines += "  { min: 90, max: 100, letter: 'A',  point: 4.0, remark: 'Excellent' },"
$lines += "  { min: 85, max: 89,  letter: 'A-', point: 3.7, remark: 'Tres Bien' },"
$lines += "  { min: 80, max: 84,  letter: 'B+', point: 3.3, remark: 'Bien' },"
$lines += "  { min: 75, max: 79,  letter: 'B',  point: 3.0, remark: 'Assez Bien' },"
$lines += "  { min: 70, max: 74,  letter: 'B-', point: 2.7, remark: 'Satisfaisant' },"
$lines += "  { min: 65, max: 69,  letter: 'C+', point: 2.3, remark: 'Passable' },"
$lines += "  { min: 60, max: 64,  letter: 'C',  point: 2.0, remark: 'Passable' },"
$lines += "  { min: 50, max: 59,  letter: 'D',  point: 1.0, remark: 'Insuffisant' },"
$lines += "  { min: 0,  max: 49,  letter: 'F',  point: 0.0, remark: 'Echec' },"
$lines += "];"
$lines += ""
$lines += "function resolveGrade(percentage: number, scheme?: any[]): { letter: string; point: number; remark: string } {"
$lines += "  const grades = (scheme && scheme.length > 0) ? scheme : DEFAULT_GRADING_SCHEME;"
$lines += "  const pct = Math.min(100, Math.max(0, percentage));"
$lines += "  const match = grades.find((g: any) => pct >= g.min && pct <= g.max);"
$lines += "  return match ? { letter: match.letter, point: match.point, remark: match.remark }"
$lines += "               : { letter: 'F', point: 0.0, remark: 'Echec' };"
$lines += "}"
$lines += ""
$lines += "function buildFallbackWeights(exams: any[]): any[] {"
$lines += "  const total = exams.reduce((s: number, e: any) => s + Number(e.weight || 1), 0);"
$lines += "  return exams.map((e: any) => ({"
$lines += "    examId: e.id, examName: e.name,"
$lines += "    categoryCode: e.assessmentCategory?.code || 'EXAM',"
$lines += "    categoryName: e.assessmentCategory?.name || e.name,"
$lines += "    weight: total > 0 ? (Number(e.weight || 1) / total) * 100 : 100 / exams.length,"
$lines += "    maxScore: Number(e.maxScore || 100),"
$lines += "  }));"
$lines += "}"
$lines += ""
$lines += "export const academicEngine = {"
$lines += ""
$lines += "  async resolveGradingScheme(blueprintId?: number): Promise<any[]> {"
$lines += "    if (!blueprintId) return DEFAULT_GRADING_SCHEME;"
$lines += "    try {"
$lines += "      const bp = await (strapi.entityService.findOne as any)('api::assessment-blueprint.assessment-blueprint', blueprintId, { populate: ['gradingScheme'] }) as any;"
$lines += "      if (bp?.gradingScheme?.grades?.length > 0) return bp.gradingScheme.grades;"
$lines += "    } catch (e) {}"
$lines += "    return DEFAULT_GRADING_SCHEME;"
$lines += "  },"
$lines += ""
$lines += "  async calculateSubjectResult(studentId: number, subjectId: number, semesterId: number, academicYearId: number): Promise<any> {"
$lines += "    const exams = await (strapi.entityService.findMany as any)('api::school-exam.school-exam', {"
$lines += "      filters: { subject: { id: subjectId }, semesterRel: { id: semesterId }, academicYear: { id: academicYearId } },"
$lines += "      populate: ['assessmentCategory', 'blueprint']"
$lines += "    }) as any[];"
$lines += "    if (exams.length === 0) return null;"
$lines += "    const examIds = exams.map((e: any) => e.id);"
$lines += "    const DIN = '`$in';"
$lines += "    const results = await (strapi.entityService.findMany as any)('api::exam-result.exam-result', {"
$lines += "      filters: { student: { id: studentId }, exam: { id: { [DIN]: examIds } }, status: { [DIN]: ['SUBMITTED', 'GRADED', 'DRAFT'] } },"
$lines += "      populate: ['exam', 'exam.assessmentCategory']"
$lines += "    }) as any[];"
$lines += "    const blueprintId = exams.find((e: any) => e.blueprint?.id)?.blueprint?.id;"
$lines += "    let categoryWeights: any[] = [];"
$lines += "    if (blueprintId) {"
$lines += "      const bp = await (strapi.entityService.findOne as any)('api::assessment-blueprint.assessment-blueprint', blueprintId) as any;"
$lines += "      categoryWeights = (bp?.categoryWeights as any[]) || [];"
$lines += "    }"
$lines += "    const useFallback = categoryWeights.length === 0;"
$lines += "    const fallbackWeights = useFallback ? buildFallbackWeights(exams) : [];"
$lines += "    const gradingScheme = await this.resolveGradingScheme(blueprintId);"
$lines += "    const scoreBreakdown: any[] = [];"
$lines += "    let totalWeightUsed = 0, totalWeightedPoints = 0;"
$lines += "    if (useFallback) {"
$lines += "      for (const fw of fallbackWeights) {"
$lines += "        const result = results.find((r: any) => r.exam?.id === fw.examId);"
$lines += "        const rawScore = result ? Number(result.marks ?? result.rawScore) : null;"
$lines += "        const maxScore = fw.maxScore || 100;"
$lines += "        const wDec = fw.weight / 100;"
$lines += "        let contributed = 0;"
$lines += "        if (rawScore !== null) { contributed = (rawScore / maxScore) * wDec * 100; totalWeightedPoints += contributed; totalWeightUsed += fw.weight; }"
$lines += "        scoreBreakdown.push({ examId: fw.examId, examName: fw.examName, category: fw.categoryName, rawScore, maxScore, weight: fw.weight, contributed: Math.round(contributed * 100) / 100, scoreStatus: rawScore !== null ? 'NUMERIC' : 'MISSING' });"
$lines += "      }"
$lines += "    } else {"
$lines += "      const catMap = new Map<string, { weight: number; maxScore: number; scores: number[]; name: string }>();"
$lines += "      for (const cw of categoryWeights) catMap.set(cw.categoryCode, { weight: Number(cw.weight), maxScore: Number(cw.maxScore || 100), scores: [], name: cw.categoryName || cw.categoryCode });"
$lines += "      for (const r of results) { const code = r.exam?.assessmentCategory?.code || 'EXAM'; const entry = catMap.get(code); if (entry) entry.scores.push(Number(r.marks ?? r.rawScore ?? 0)); }"
$lines += "      for (const [code, entry] of catMap.entries()) {"
$lines += "        const avg = entry.scores.length > 0 ? entry.scores.reduce((a: number, b: number) => a + b, 0) / entry.scores.length : null;"
$lines += "        const wDec = entry.weight / 100;"
$lines += "        let contributed = 0;"
$lines += "        if (avg !== null) { contributed = (avg / entry.maxScore) * wDec * 100; totalWeightedPoints += contributed; totalWeightUsed += entry.weight; }"
$lines += "        scoreBreakdown.push({ categoryCode: code, category: entry.name, scores: entry.scores, avgScore: avg !== null ? Math.round(avg * 100) / 100 : null, maxScore: entry.maxScore, weight: entry.weight, contributed: Math.round(contributed * 100) / 100, scoreStatus: avg !== null ? 'NUMERIC' : 'MISSING' });"
$lines += "      }"
$lines += "    }"
$lines += "    const percentage = totalWeightUsed > 0 ? Math.round((totalWeightedPoints / (totalWeightUsed / 100)) * 100) / 100 : 0;"
$lines += "    const gradeInfo = resolveGrade(percentage, gradingScheme);"
$lines += "    return { subjectId, semesterId, academicYearId, percentage, letterGrade: gradeInfo.letter, gradePoint: gradeInfo.point, remark: gradeInfo.remark, scoreBreakdown, totalWeightUsed, hasScores: results.length > 0, blueprintId: blueprintId || null };"
$lines += "  },"
$lines += ""
$lines += "  async calculatePeriodResult(studentId: number, semesterId: number, academicYearId: number): Promise<any> {"
$lines += "    const examsInPeriod = await (strapi.entityService.findMany as any)('api::school-exam.school-exam', {"
$lines += "      filters: { semesterRel: { id: semesterId }, academicYear: { id: academicYearId } },"
$lines += "      populate: ['subject', 'classe', 'classe.students']"
$lines += "    }) as any[];"
$lines += "    const studentExams = examsInPeriod.filter((e: any) => (e.classe?.students || []).some((s: any) => s.id === studentId));"
$lines += "    const subjectMap = new Map<number, any>();"
$lines += "    for (const exam of studentExams) { if (exam.subject?.id) subjectMap.set(exam.subject.id, exam.subject); }"
$lines += "    const subjectResults: any[] = [];"
$lines += "    for (const [subjectId, subject] of subjectMap.entries()) {"
$lines += "      const result = await this.calculateSubjectResult(studentId, subjectId, semesterId, academicYearId);"
$lines += "      if (result) subjectResults.push({ ...result, subjectName: subject.name, subjectCode: subject.code });"
$lines += "    }"
$lines += "    const valid = subjectResults.filter((r: any) => r.hasScores);"
$lines += "    const periodAvg = valid.length > 0 ? Math.round(valid.reduce((s: number, r: any) => s + r.percentage, 0) / valid.length * 100) / 100 : 0;"
$lines += "    const periodGPA = valid.length > 0 ? Math.round(valid.reduce((s: number, r: any) => s + r.gradePoint, 0) / valid.length * 100) / 100 : 0;"
$lines += "    return { semesterId, academicYearId, subjectResults, periodAverage: periodAvg, periodGPA, subjectCount: valid.length };"
$lines += "  },"
$lines += ""
$lines += "  async calculateAnnualResult(studentId: number, academicYearId: number): Promise<any> {"
$lines += "    const semesters = await (strapi.entityService.findMany as any)('api::semester.semester', {"
$lines += "      filters: { academicYear: { id: academicYearId } }, sort: [{ order: 'asc' }]"
$lines += "    }) as any[];"
$lines += "    const periodResults: any[] = [];"
$lines += "    for (const sem of semesters) {"
$lines += "      const r = await this.calculatePeriodResult(studentId, sem.id, academicYearId);"
$lines += "      periodResults.push({ ...r, semesterName: sem.name, periodType: sem.periodType || 'SEMESTER', semesterOrder: sem.order || 1 });"
$lines += "    }"
$lines += "    const all = periodResults.flatMap((p: any) => p.subjectResults.filter((r: any) => r.hasScores));"
$lines += "    const annualAverage = all.length > 0 ? Math.round(all.reduce((s: number, r: any) => s + r.percentage, 0) / all.length * 100) / 100 : 0;"
$lines += "    const annualGPA = all.length > 0 ? Math.round(all.reduce((s: number, r: any) => s + r.gradePoint, 0) / all.length * 100) / 100 : 0;"
$lines += "    const gi = resolveGrade(annualAverage);"
$lines += "    return { academicYearId, periodResults, annualAverage, annualGPA, annualGrade: gi.letter, annualRemark: gi.remark, totalSubjects: new Set(all.map((r: any) => r.subjectId)).size, totalPeriods: periodResults.length, periodsWithData: periodResults.filter((p: any) => p.subjectCount > 0).length };"
$lines += "  },"
$lines += ""
$lines += "  async generateTranscriptAuto(studentId: number, academicYearId: number): Promise<any> {"
$lines += "    const crypto = require('crypto');"
$lines += "    const student = await (strapi.entityService.findOne as any)('plugin::users-permissions.user', studentId, { fields: ['id','userId','username','email','birthDate','phoneNumber'], populate: ['enrolledClasses'] }) as any;"
$lines += "    if (!student) throw new Error('Student not found');"
$lines += "    const academicYear = await (strapi.entityService.findOne as any)('api::academic-year.academic-year', academicYearId) as any;"
$lines += "    if (!academicYear) throw new Error('Academic year not found');"
$lines += "    let schoolInfo = { name: '2CS COMPLEXE SCOLAIRE', address: '', email: '', phone: '' };"
$lines += "    try {"
$lines += "      const ciList = await (strapi.entityService.findMany as any)('api::contact-info.contact-info', { populate: ['phones','email'] }) as any[];"
$lines += "      const ci = Array.isArray(ciList) ? ciList[0] : ciList;"
$lines += "      if (ci) { schoolInfo.address = ci.address||''; schoolInfo.phone = ci.phones?.[0]?.phones||''; schoolInfo.email = ci.email?.[0]?.address||''; }"
$lines += "      const nbs = await (strapi.entityService.findMany as any)('api::navbar.navbar') as any[];"
$lines += "      const nb = Array.isArray(nbs) ? nbs[0] : nbs;"
$lines += "      if (nb?.title) schoolInfo.name = nb.title;"
$lines += "    } catch(e) {}"
$lines += "    const annualResult = await this.calculateAnnualResult(studentId, academicYearId);"
$lines += "    const hashInput = 'auto-' + studentId + '-' + academicYearId;"
$lines += "    const hash = crypto.createHash('md5').update(hashInput).digest('hex').substring(0,8).toUpperCase();"
$lines += "    const yearCode = (academicYear.name || '').replace(/[^A-Z0-9]/gi, '');"
$lines += "    const refNum = 'TR-AUTO-' + (student.userId||student.id) + '-' + yearCode + '-' + hash;"
$lines += "    const generationDate = new Date().toISOString();"
$lines += "    const friendlyDate = new Date().toLocaleDateString('fr-FR', { year:'numeric', month:'long', day:'numeric' });"
$lines += "    try {"
$lines += "      const existing = await (strapi.entityService.findMany as any)('api::transcript.transcript', { filters: { referenceNumber: refNum } }) as any[];"
$lines += "      const payload: any = { referenceNumber: refNum, generationDate, gpa: annualResult.annualGPA, averageScore: annualResult.annualAverage, student: studentId, academicYear: academicYearId, class: student.enrolledClasses?.[0]?.id||null, semesters: annualResult.periodResults.map((p: any) => p.semesterId), terms: [] };"
$lines += "      if (existing.length > 0) { await (strapi.entityService.update as any)('api::transcript.transcript', existing[0].id, { data: payload }); }"
$lines += "      else { await (strapi.entityService.create as any)('api::transcript.transcript', { data: payload }); }"
$lines += "    } catch(dbErr) { strapi.log.warn('Failed to save auto-transcript:', dbErr); }"
$lines += "    return { student: { id: student.id, userId: student.userId, name: student.username, email: student.email, birthDate: student.birthDate, phoneNumber: student.phoneNumber, classes: (student.enrolledClasses||[]).map((c: any) => c.name) }, school: schoolInfo, academicYear: { id: academicYearId, name: academicYear.name }, annualResult, summary: { annualAverage: annualResult.annualAverage, annualGPA: annualResult.annualGPA, annualGrade: annualResult.annualGrade, annualRemark: annualResult.annualRemark, totalSubjects: annualResult.totalSubjects, totalPeriods: annualResult.totalPeriods }, metadata: { referenceNumber: refNum, generationDate: friendlyDate, academicYearName: academicYear.name, generatedAt: generationDate } };"
$lines += "  },"
$lines += ""
$lines += "  async saveCalculatedResult(studentId: number, subjectId: number, semesterId: number, academicYearId: number, classId?: number) {"
$lines += "    const result = await this.calculateSubjectResult(studentId, subjectId, semesterId, academicYearId);"
$lines += "    if (!result) return null;"
$lines += "    const existing = await (strapi.entityService.findMany as any)('api::academic-result.academic-result', { filters: { student: { id: studentId }, subject: { id: subjectId }, semester: { id: semesterId }, academicYear: { id: academicYearId } } }) as any[];"
$lines += "    const payload: any = { totalScore: result.percentage, percentage: result.percentage, letterGrade: result.letterGrade, gradePoint: result.gradePoint, remarks: result.remark, scoreBreakdown: result.scoreBreakdown, calculatedAt: new Date().toISOString(), status: 'CALCULATED', student: studentId, subject: subjectId, semester: semesterId, academicYear: academicYearId, ...(classId ? { classe: classId } : {}), ...(result.blueprintId ? { blueprint: result.blueprintId } : {}) };"
$lines += "    if (existing.length > 0) return (strapi.entityService.update as any)('api::academic-result.academic-result', existing[0].id, { data: payload });"
$lines += "    return (strapi.entityService.create as any)('api::academic-result.academic-result', { data: payload });"
$lines += "  },"
$lines += ""
$lines += "  async recalculateStudent(studentId: number, academicYearId: number): Promise<{ updated: number }> {"
$lines += "    const semesters = await (strapi.entityService.findMany as any)('api::semester.semester', { filters: { academicYear: { id: academicYearId } } }) as any[];"
$lines += "    let updated = 0;"
$lines += "    for (const sem of semesters) {"
$lines += "      const pr = await this.calculatePeriodResult(studentId, sem.id, academicYearId);"
$lines += "      for (const sr of pr.subjectResults) { if (sr.hasScores) { await this.saveCalculatedResult(studentId, sr.subjectId, sem.id, academicYearId); updated++; } }"
$lines += "    }"
$lines += "    return { updated };"
$lines += "  },"
$lines += ""
$lines += "  async getDynamicGradebook(classId: number, subjectId?: number, semesterId?: number): Promise<any> {"
$lines += "    const cls = await (strapi.entityService.findOne as any)('api::school-class.school-class', classId, { populate: ['students','academicYear'] }) as any;"
$lines += "    const students = cls?.students || [];"
$lines += "    const examFilters: any = { classe: { id: classId } };"
$lines += "    if (subjectId) examFilters.subject = { id: subjectId };"
$lines += "    if (semesterId) examFilters.semesterRel = { id: semesterId };"
$lines += "    const exams = await (strapi.entityService.findMany as any)('api::school-exam.school-exam', { filters: examFilters, populate: ['subject','assessmentCategory','semesterRel'], sort: [{ date: 'asc' }] }) as any[];"
$lines += "    if (exams.length === 0) return { classId, className: cls?.name, columns: [], rows: [] };"
$lines += "    const examIds = exams.map((e: any) => e.id);"
$lines += "    const DIN = '`$in';"
$lines += "    const allResults = await (strapi.entityService.findMany as any)('api::exam-result.exam-result', { filters: { exam: { id: { [DIN]: examIds } } }, populate: ['student','exam'] }) as any[];"
$lines += "    const resultMap = new Map<number, Map<number, any>>();"
$lines += "    for (const r of allResults) { if (!r.student?.id) continue; if (!resultMap.has(r.student.id)) resultMap.set(r.student.id, new Map()); resultMap.get(r.student.id)!.set(r.exam?.id, r); }"
$lines += "    const columns = exams.map((e: any) => ({ examId: e.id, examName: e.name, subjectName: e.subject?.name, subjectId: e.subject?.id, categoryCode: e.assessmentCategory?.code||'EXAM', categoryName: e.assessmentCategory?.name||e.name, semesterName: e.semesterRel?.name, semesterId: e.semesterRel?.id, maxScore: e.maxScore||100, weight: e.weight||0, dueDate: e.dueDate, examStatus: e.examStatus }));"
$lines += "    const rows = students.map((student: any) => {"
$lines += "      const sRes = resultMap.get(student.id) || new Map();"
$lines += "      const scores: any = {}; let totalValid = 0; let totalScore = 0;"
$lines += "      for (const col of columns) { const r = sRes.get(col.examId); if (r) { scores[col.examId] = { resultId: r.id, marks: r.marks??r.rawScore, maxScore: col.maxScore, letterGrade: r.letterGrade, scoreStatus: r.scoreStatus||'NUMERIC', status: r.status }; totalValid++; totalScore += Number(r.marks??r.rawScore??0); } else { scores[col.examId] = null; } }"
$lines += "      const average = totalValid > 0 ? Math.round((totalScore / totalValid) * 100) / 100 : null;"
$lines += "      const gi2 = average !== null ? resolveGrade(average) : null;"
$lines += "      return { studentId: student.id, studentName: student.username, studentUserId: student.userId, scores, average, letterGrade: gi2?.letter||null, gradePoint: gi2?.point||null };"
$lines += "    }).sort((a: any, b: any) => (a.studentName||'').localeCompare(b.studentName||''));"
$lines += "    return { classId, className: cls?.name, academicYearId: cls?.academicYear?.id, columns, rows };"
$lines += "  },"
$lines += "};"
$lines += ""
$lines += "export default academicEngine;"
$lines | Set-Content -Path $dest -Encoding UTF8
Write-Output "Done: $($(Get-Item $dest).Length) bytes"
